# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and deploy Python app to Azure Web App - user-management-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies with binary-only
        run: |
          pip install --upgrade pip
          # First try with binary-only installation
          pip install --only-binary :all: -r requirements.txt || {
            echo "Binary installation failed, creating wheels with build dependencies..."
            sudo apt-get update
            sudo apt-get install -y build-essential python3-dev
            pip install wheel
            pip wheel --no-deps -r requirements.txt -w wheelhouse/
            pip install --no-index --find-links=wheelhouse/ -r requirements.txt
          }

      - name: Run Tests
        run: pytest test_app.py

      - name: Package wheelhouse for deployment
        run: |
          # Include the wheelhouse directory if it exists
          [ -d wheelhouse ] && zip -r wheelhouse.zip wheelhouse/ || echo "No wheelhouse directory"
          zip -r release.zip . -x "venv/*" ".git/*" "wheelhouse/*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            wheelhouse.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Restore wheelhouse (if exists)
        run: |
          [ -f wheelhouse.zip ] && unzip -o wheelhouse.zip || echo "No wheelhouse found"

      - name: Unzip main artifact
        run: unzip -o release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'user-management-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_76D6DE8CE9B24A019CD70733FCEF07D6 }}